### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ReinforceZwei** [ReinforceZwei/scriptable-calendar-widget#1]
- [x] There is relative date formatter built-in with locale string for "today"
- [x] When no events, display a check mark with today date + week day
- [x] Make some built-in theme (e.g. light, dark, sakura?)
- [x] Maybe separate color setting into new object
